// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnrolyuqydclczzoirvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZucm9seXVxeWRjbGN6em9pcnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzIzNTYsImV4cCI6MjA2MTk0ODM1Nn0.z-VcSEposkRpbDfEiyy2re1PRZ1sSmM6_kVD28hGS4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);